[MINOR] [BUILD] Declare ivy dependency in root pom.
Without this, any dependency that pulls ivy transitively may override
the version and potentially cause issue. In my machine, the hive tests
were pulling an old version of ivy, and subsequently failing with a
"NoSuchMethodError".

Author: Marcelo Vanzin <vanzin@cloudera.com>

Closes #5893 from vanzin/ivy-dep-fix and squashes the following commits:

ea2112d [Marcelo Vanzin] [minor] [build] Declare ivy dependency in root pom.

(cherry picked from commit c5790a2f772168351c18bb0da51a124cee89a06f)
Signed-off-by: Sean Owen <sowen@cloudera.com>
(cherry picked from commit b34b5bdf520931ece2549c0662d8fde9435afd1c)