[SPARK-25918][SQL] LOAD DATA LOCAL INPATH should handle a relative path
Unfortunately, it seems that we missed this in 2.4.0. In Spark 2.4, if the default file system is not the local file system, `LOAD DATA LOCAL INPATH` only works in case of absolute paths. This PR aims to fix it to support relative paths. This is a regression in 2.4.0.

```scala
$ ls kv1.txt
kv1.txt

scala> spark.sql("LOAD DATA LOCAL INPATH 'kv1.txt' INTO TABLE t")
org.apache.spark.sql.AnalysisException: LOAD DATA input path does not exist: kv1.txt;
```

Pass the Jenkins

Closes #22927 from dongjoon-hyun/SPARK-LOAD.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>
(cherry picked from commit e91b607719886b57d1550a70c0f9df4342d72989)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>
(cherry picked from commit 8c508da2add315ca1615219ae444bff99b1f9eca)

Change-Id: I15e6156c61bde754423d049db95d4a1dd63bc76f